[package]
name = "rpo-core"
description = "Core astrodynamics library for RPO mission planning"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "MIT OR Apache-2.0"

[features]
test-fixtures = []
wasm = ["dep:tsify-next", "dep:wasm-bindgen"]

[dependencies]
nalgebra = { workspace = true, features = ["serde-serialize"] }
hifitime = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tsify-next = { version = "0.5", optional = true, default-features = false, features = ["js"] }
wasm-bindgen = { version = "0.2", optional = true }

[dev-dependencies]
serde_json = { workspace = true }
criterion = { version = "0.5", features = ["html_reports"] }
rand = "0.8"
rand_chacha = "0.3"
rand_distr = "0.4"

[[bench]]
name = "analytical"
harness = false

[[bench]]
name = "frames"
harness = false

[[bench]]
name = "lambert"
harness = false
