[package]
name = "rpo-cli"
description = "CLI tool for RPO mission planning"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license = "AGPL-3.0-or-later"

[dependencies]
rpo-core = { path = "../rpo-core" }
rpo-nyx = { path = "../rpo-nyx" }
anise = { workspace = true }
hifitime = { workspace = true }
clap = { version = "4", features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
nalgebra = { workspace = true }
thiserror = { workspace = true }
indicatif = "0.17"
clap_complete = "4"

[dev-dependencies]
serde_json = { workspace = true }
